name: Code Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-versions: ['7.1', '7.2']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          runner: ubuntu-18.04

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install composer packages
        run: composer install --prefer-source --no-interaction

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Tests Coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
